package com.ydg.web_taskList.user.po;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

import com.ydg.web_taskList.user.validated.validatedGroup1;

public abstract class User implements Nullable {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.userID
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	private String userid;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.userName
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	@NotBlank(message = "{username.not.null}", groups = { validatedGroup1.class })
	@Length(max = 50, min = 3, message = "{username.login.ErrorMessage}", groups = { validatedGroup1.class })
	private String username;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.userPassword
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	@NotBlank(message = "{userpassword.not.null}", groups = { validatedGroup1.class })
	@Pattern(regexp = "^([A-Z]|[a-z]|[0-9]|[`~!@#$%^&*()+=|{}':;',\\\\[\\\\].<>/?~！@#￥%……&*（）——+|{}【】‘；：”“’。，、？]){6,20}$", message = "{userpassword.login.ErrorMessage}", groups = { validatedGroup1.class })
	private String userpassword;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user.userEmail
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	@NotBlank(message = "{useremail.not.null}")
	@Email(message = "{email.format}")
	private String useremail;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.userID
	 *
	 * @return the value of user.userID
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.userID
	 *
	 * @param userid the value for user.userID
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.userName
	 *
	 * @return the value of user.userName
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.userName
	 *
	 * @param username the value for user.userName
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.userPassword
	 *
	 * @return the value of user.userPassword
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	public String getUserpassword() {
		return userpassword;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.userPassword
	 *
	 * @param userpassword the value for user.userPassword
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword == null ? null : userpassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user.userEmail
	 *
	 * @return the value of user.userEmail
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	public String getUseremail() {
		return useremail;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user.userEmail
	 *
	 * @param useremail the value for user.userEmail
	 *
	 * @mbggenerated Tue Jun 20 13:47:09 CST 2017
	 */
	public void setUseremail(String useremail) {
		this.useremail = useremail == null ? null : useremail.trim();
	}

	/**
	 * 判断是否为null对象
	 */
	@Override
	public abstract boolean isnull() throws Exception;

	public abstract void forward(User formUserCustom, HttpServletRequest request,
			HttpServletResponse response) throws Exception;
}